"""Diffusion-based segmentation (MedSegDiff-style) with genetic conditioning.

The mask is generated by a conditional denoising diffusion process: a
time-conditioned, attention-gated U-Net predicts the clean mask (x0) from a noisy
mask, conditioned on the MRI image (channel concat + multi-scale skips), on the
previous mask estimate (self-conditioning), and -- via FiLM -- on the genetic
latent (real or JEPA-imputed). This makes the same diffusion principle that
drives our cross-modal latent prediction also drive dense mask prediction.

Competitiveness upgrades over a naive diffusion segmenter:
  * x0-parameterisation + per-noise-level BCE/Dice supervision (stable, strong),
  * self-conditioning (Chen et al.) -- feed the previous x0 estimate back in,
  * attention-gated skip connections (as in the best discriminative backbone),
  * multi-sample DDIM ensembling at inference (STAPLE-like averaging).

Interface (via train_segmentation's diffusion branch):
  loss(image, mask, gene, gene_mode)            -> scalar (+ gene_hat, gene_latent)
  segment(image, gene, gene_mode, n_ensemble)   -> {logits, prob}
"""
import torch
import torch.nn as nn
import torch.nn.functional as F

from models.diffusion_predictor import (SinusoidalTimeEmbedding,
                                         cosine_alpha_bar)
from models.seg_backbones import AttentionGate
from models.segmentation import FiLM, GeneEncoderMLP, dice_loss, tversky_loss


class TimeConvBlock(nn.Module):
    def __init__(self, cin, cout, t_dim):
        super().__init__()
        self.c1 = nn.Conv2d(cin, cout, 3, padding=1)
        self.c2 = nn.Conv2d(cout, cout, 3, padding=1)
        self.n1 = nn.GroupNorm(8, cout)
        self.n2 = nn.GroupNorm(8, cout)
        self.temb = nn.Linear(t_dim, cout)
        self.act = nn.SiLU()

    def forward(self, x, t):
        h = self.act(self.n1(self.c1(x)))
        h = h + self.temb(t)[:, :, None, None]
        return self.act(self.n2(self.c2(h)))


class MaskDenoiser(nn.Module):
    """Attention U-Net denoiser predicting the clean mask (x0 as logits)."""

    def __init__(self, img_ch=3, base=32, gene_latent=128, t_dim=128):
        super().__init__()
        c = [base, base * 2, base * 4, base * 8]
        self.time = nn.Sequential(SinusoidalTimeEmbedding(t_dim),
                                  nn.Linear(t_dim, t_dim), nn.SiLU())
        self.pool = nn.MaxPool2d(2)
        # input: image (img_ch) + noisy mask (1) + self-conditioning estimate (1)
        self.e1 = TimeConvBlock(img_ch + 2, c[0], t_dim)
        self.e2 = TimeConvBlock(c[0], c[1], t_dim)
        self.e3 = TimeConvBlock(c[1], c[2], t_dim)
        self.b = TimeConvBlock(c[2], c[3], t_dim)
        self.img2gene = nn.Sequential(nn.Linear(c[3], gene_latent), nn.GELU(),
                                      nn.Linear(gene_latent, gene_latent))
        self.u3 = nn.ConvTranspose2d(c[3], c[2], 2, 2); self.a3 = AttentionGate(c[2], c[2], c[2] // 2)
        self.d3 = TimeConvBlock(c[3], c[2], t_dim); self.f3 = FiLM(gene_latent, c[2])
        self.u2 = nn.ConvTranspose2d(c[2], c[1], 2, 2); self.a2 = AttentionGate(c[1], c[1], c[1] // 2)
        self.d2 = TimeConvBlock(c[2], c[1], t_dim); self.f2 = FiLM(gene_latent, c[1])
        self.u1 = nn.ConvTranspose2d(c[1], c[0], 2, 2); self.a1 = AttentionGate(c[0], c[0], c[0] // 2)
        self.d1 = TimeConvBlock(c[1], c[0], t_dim); self.f1 = FiLM(gene_latent, c[0])
        self.out = nn.Conv2d(c[0], 1, 1)

    def forward(self, x_t, image, self_cond, t, cond):
        temb = self.time(t)
        h = torch.cat([x_t, self_cond, image], dim=1)
        e1 = self.e1(h, temb)
        e2 = self.e2(self.pool(e1), temb)
        e3 = self.e3(self.pool(e2), temb)
        b = self.b(self.pool(e3), temb)
        gene_hat = self.img2gene(F.adaptive_avg_pool2d(b, 1).flatten(1))
        u3 = self.u3(b); d3 = self.f3(self.d3(torch.cat([u3, self.a3(u3, e3)], 1), temb), cond)
        u2 = self.u2(d3); d2 = self.f2(self.d2(torch.cat([u2, self.a2(u2, e2)], 1), temb), cond)
        u1 = self.u1(d2); d1 = self.f1(self.d1(torch.cat([u1, self.a1(u1, e1)], 1), temb), cond)
        return self.out(d1), gene_hat


class DiffusionSeg(nn.Module):
    is_diffusion = True

    def __init__(self, in_ch=3, n_classes=1, gene_dim=16, gene_latent=128,
                 base=32, dropout=0.2, timesteps=1000, sample_steps=25,
                 eval_ensemble=4):
        super().__init__()
        self.timesteps = timesteps
        self.sample_steps = sample_steps
        self.eval_ensemble = eval_ensemble
        self.denoiser = MaskDenoiser(in_ch, base, gene_latent)
        self.gene_encoder = GeneEncoderMLP(gene_dim, gene_latent, dropout=dropout)
        self.register_buffer("alpha_bar", cosine_alpha_bar(timesteps))
        self.gene_latent_dim = gene_latent

    def _cond(self, gene, gene_hat, gene_mode):
        zt = self.gene_encoder(gene) if gene is not None else None
        if gene_mode == "none":
            return None, zt
        if gene_mode == "jepa":
            return gene_hat, zt
        return (zt if zt is not None else gene_hat), zt

    def _gene_cond(self, image, x_ref, gene, gene_mode):
        B = image.size(0)
        z = torch.zeros_like(x_ref)
        with torch.no_grad():
            _, gh0 = self.denoiser(z, image, z, torch.zeros(B, device=image.device),
                                   None)
        return self._cond(gene, gh0, gene_mode)

    def loss(self, image, mask, gene=None, gene_mode="true"):
        x0 = mask * 2 - 1                                     # {0,1} -> {-1,1}
        B = x0.size(0)
        t = torch.randint(0, self.timesteps, (B,), device=x0.device)
        ab = self.alpha_bar[t].view(B, 1, 1, 1)
        noise = torch.randn_like(x0)
        x_t = ab.sqrt() * x0 + (1 - ab).sqrt() * noise
        cond, zt = self._gene_cond(image, x0, gene, gene_mode)
        # self-conditioning: half the time, supply a detached first estimate
        self_cond = torch.zeros_like(x0)
        if torch.rand(()) < 0.5:
            with torch.no_grad():
                m0, _ = self.denoiser(x_t, image, self_cond, t.float(), cond)
                self_cond = torch.tanh(m0).detach()
        m_hat, gene_hat = self.denoiser(x_t, image, self_cond, t.float(), cond)
        x0_hat = torch.tanh(m_hat)
        # Segmentation supervision dominates; the diffusion x0-MSE is downweighted
        # so it does not pull every pixel toward the (background) mean and collapse
        # the mask to empty. Tversky (beta>alpha) penalizes missed tumor.
        loss_diff = F.mse_loss(x0_hat, x0)
        loss_seg = (F.binary_cross_entropy_with_logits(m_hat, mask)
                    + tversky_loss(m_hat, mask, alpha=0.3, beta=0.7))
        return 0.2 * loss_diff + loss_seg, gene_hat, zt

    @torch.no_grad()
    def segment(self, image, gene=None, gene_mode="true", steps=None,
                n_ensemble=None):
        steps = steps or self.sample_steps
        n_ensemble = n_ensemble or 1
        B = image.size(0)
        dev = image.device
        probs = []
        for _ in range(n_ensemble):
            x = torch.randn(B, 1, image.shape[2], image.shape[3], device=dev)
            cond, _ = self._gene_cond(image, x, gene, gene_mode)
            ts = torch.linspace(self.timesteps - 1, 0, steps, device=dev).long()
            self_cond = torch.zeros_like(x)
            m_hat = None
            for i in range(steps):
                t = ts[i]
                ab_t = self.alpha_bar[t]
                m_hat, _ = self.denoiser(x, image, self_cond, t.float().expand(B), cond)
                x0_hat = torch.tanh(m_hat)
                self_cond = x0_hat
                eps_hat = (x - ab_t.sqrt() * x0_hat) / (1 - ab_t).sqrt()
                ab_prev = self.alpha_bar[ts[i + 1]] if i + 1 < steps else \
                    torch.tensor(1.0, device=dev)
                x = ab_prev.sqrt() * x0_hat + (1 - ab_prev).sqrt() * eps_hat
            probs.append(torch.sigmoid(m_hat))
        prob = torch.stack(probs).mean(0)
        pc = prob.clamp(1e-4, 1 - 1e-4)
        return {"logits": torch.log(pc / (1 - pc)), "prob": prob}

    def forward(self, image, gene=None, gene_mode="true"):
        return self.segment(image, gene, gene_mode, n_ensemble=1)
